apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-api
spec:
  selector:
    matchLabels:
      app: service-api
  template:
    metadata:
      labels:
        app: service-api
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
      - name: zipkin
        image: openzipkin/zipkin:2.21
        ports:
        - name: zipkin
          containerPort: 9411
      - name: app
        image: service-api-amd64:1.0
        env:
        - name: SERVICE_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: db_host
        - name: SERVICE_ZIPKIN_REPORTER_URI
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: zipkin_reporter_uri
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_PODNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBERNETES_NAMESPACE_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KUBERNETES_NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - name: app
          containerPort: 3000
        - name: app-debug
          containerPort: 4000
        readinessProbe:
          httpGet:
            path: /readiness
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /liveness
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: service-api
spec:
  selector:
    service: service-api
  ports:
  - name: zipkin
    port: 9411
    targetPort: zipkin
  - name: app
    port: 3000
    targetPort: app
  - name: app-debug
    port: 4000
    targetPort: app-debug